services:
  _defaults:
    public: true
    autowire: true

  huh.encore.listener.hooks:
    class: HeimrichHannot\EncoreBundle\EventListener\HookListener
    autowire: false
    arguments:
      ['@service_container', '@twig', '@HeimrichHannot\EncoreBundle\Asset\EntrypointsJsonLookup', '@huh.encore.cache']