services:
  HeimrichHannot\EncoreBundle\Asset\EntrypointsJsonLookup:
    arguments:
      - "@service_container"
      - "@webpack_encore.cache"

  huh.encore.choice.entry:
    class: HeimrichHannot\EncoreBundle\Choice\EntryChoice
    public: true
    arguments:
      - "@service_container"
      - "@HeimrichHannot\\EncoreBundle\\Asset\\EntrypointsJsonLookup"
  huh.encore.choice.template.imports:
    class: HeimrichHannot\EncoreBundle\Choice\ImportsTemplateChoice
    public: true
    arguments:
      - "@contao.framework"

  huh.encore.cache:
    class: Symfony\Component\Cache\Adapter\TagAwareAdapter
    arguments:
      - '@huh.encore.cache.item'

  huh.encore.cache.item:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      - 'huh_encore.entries'
      - 0
      - '%kernel.cache_dir%'