services:
  _defaults:
    autowire: true
    bind:
      $bundleConfig: '%huh_encore%'
      $webDir: '%contao.web_dir%'
      $encoreCache: '@webpack_encore.cache'
      Psr\Cache\CacheItemPoolInterface: "@webpack_encore.cache"

  HeimrichHannot\EncoreBundle\:
    resource: "../../{Asset,Collection,Command,DataContainer,Dca,EventListener,Helper,Migration}/*"
    exclude: '../../Asset/{EntrypointCollection.php,EntrypointsJsonLookup.php}'
    public: true
    autoconfigure: true

  HeimrichHannot\EncoreBundle\Command\PrepareCommand:
    public: false
    tags:
      - { name: 'console.command', command: 'huh:encore:prepare' }
      - { name: 'console.command', command: 'encore:prepare' }


  huh.encore.asset.frontend:
    alias: HeimrichHannot\EncoreBundle\Asset\FrontendAsset
    public: true

  HeimrichHannot\EncoreBundle\Asset\EntrypointsJsonLookup:
    bind:
      Psr\Cache\CacheItemPoolInterface: "@webpack_encore.cache"

  huh.encore.asset.template:
    alias: HeimrichHannot\EncoreBundle\Asset\TemplateAsset
    public: true

  huh.encore.choice.entry:
    class: HeimrichHannot\EncoreBundle\Choice\EntryChoice
    public: true

  huh.encore.choice.template.imports:
    class: HeimrichHannot\EncoreBundle\Choice\ImportsTemplateChoice
    public: true
    deprecated: 'The "%service_id%" service alias is deprecated since 1.19.0.'

  huh.encore.listener.hooks: '@HeimrichHannot\EncoreBundle\EventListener\HookListener'

#  huh.encore.listener.hooks:
#    class: HeimrichHannot\EncoreBundle\EventListener\HookListener
#  HeimrichHannot\EncoreBundle\EventListener\HookListener: '@huh.encore.listener.hooks'

#  HeimrichHannot\EncoreBundle\EventListener\GeneratePageListener: ~