services:
  _defaults:
    autowire: true
    bind:
      $bundleConfig: '%huh_encore%'
      $webDir: '%contao.web_dir%'
      $encoreCache: '@webpack_encore.cache'
      Psr\Cache\CacheItemPoolInterface: "@webpack_encore.cache"

  HeimrichHannot\EncoreBundle\:
    resource: "../src/{Asset,Collection,Command,DataContainer,EventListener,Helper}/*"
    exclude: '../src/Asset/{EntrypointCollection.php}'
    public: true
    autoconfigure: true

  huh.encore.asset.frontend:
    alias: HeimrichHannot\EncoreBundle\Asset\FrontendAsset
    public: true

  huh.encore.asset.template:
    alias: HeimrichHannot\EncoreBundle\Asset\TemplateAsset
    public: true