<?php

$lang = &$GLOBALS['TL_LANG']['tl_page'];

/**
 * Fields
 */
$lang['addEncore'][0]                        = 'Activate Webpack Encore';
$lang['addEncore'][1]                        = 'Choose this option if you want to activate Encore support.';
$lang['encorePublicPath'][0]                 = 'Public path';
$lang['encorePublicPath'][1]                 =
    'Set the path relative to the /web-
    Folder, where the asset files generated by Encore will be stored (typicall: build).';
$lang['addEncoreSharedEntry'][0]             = 'Add shared entry';
$lang['addEncoreSharedEntry'][1]             = 'Select if you added an shared entry in your webpack webpack.config.js.';
$lang['encoreSharedEntryName'][0]            = 'Shared entry name';
$lang['encoreSharedEntryName'][1]            =
    'Enter the name of the shared entry as set in Encore.createSharedEntry() as first parameter.';
$lang['addDynamicEncoreImports'][0]          = 'Active dynamic imports';
$lang['addDynamicEncoreImports'][1]          =
    'Choose this option if your JavaScript files contain dynamic imports via webpack-Operators "import()".';
$lang['addEncoreBabelPolyfill'][0]           = 'babel-polyfill hinzufügen (für IE <= 11)';
$lang['addEncoreBabelPolyfill'][1]           =
    'Choose this option if you need support for Internet Exlporer version <= 11. The polyfill which e.g. provide promises support is usually not needed in modern browsers (also Edge).';
$lang['encoreBabelPolyfillEntryName'][0]     = 'babel-polyfill-Entry-Name';
$lang['encoreBabelPolyfillEntryName'][1]     =
    'Enter the name of babel-polyfill-Entry as set in Encore.addEntry() as first parameter.';
$lang['encoreEntries'][0]                    = 'Active Entries';
$lang['encoreEntries'][1]                    =
    'Select webpack entries that should be rendered on this and all inheriting pages. You can overwrite this setting on inheriting pages due page inheritance.';
$lang['encoreEntries_entry'][0]              = 'Entries';
$lang['encoreEntries_active'][0]             = 'Active';
$lang['encoreStylesheetsImportsTemplate'][0] = 'Stylesheet import template';
$lang['encoreStylesheetsImportsTemplate'][1] = 'Choose an custom stylesheet import template.';
$lang['encoreScriptsImportsTemplate'][0]     = 'Javascript import template';
$lang['encoreScriptsImportsTemplate'][1]     = 'Choose a custom javascript import template.';

/**
 * Legends
 */
$lang['encore_legend'] = 'Encore';